# $FreeBSD$

PORTNAME=	spuce
PORTVERSION=	0.4.3
CATEGORIES=	audio

MAINTAINER=	sghctoma@gmail.com
COMMENT=	DSP digital filtering library - IIR/FIR filtering

LICENSE=	BSL

USE_GITHUB=	yes
GH_ACCOUNT=	audiofilter

USES=	cmake

.include <bsd.port.mk>
