# $FreeBSD$

PORTNAME=	garmintools
PORTVERSION=	0.10
CATEGORIES=	astro
#MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}garmintools-0.10.tar.gz
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}

LICENSE=	GPLv2

USES=		gmake
GNU_CONFIGURE=	yes
CONFIGURE_ARGS= CFLAGS="-g -O2 -fPIC"

MAINTAINER=	sghctoma@gmail.com
COMMENT=	Provides users with the ability to communicate with various Garmin sport watches and bike computers.
.include <bsd.port.mk>
